In [1]:
import numpy as np

数组与数的计算

In [3]:
a1=np.random.random((3,4))
a1

array([[0.61792586, 0.89529278, 0.04443807, 0.13183565],
       [0.31657528, 0.19702116, 0.61259427, 0.09872084],
       [0.10115348, 0.26128811, 0.31524103, 0.08102474]])

In [5]:
#如果现在我要a1乘以10
#以上列子是相乘，其实相加，相减，相除也都是类似的
a2=a1*10
a2

array([[6.17925863, 8.95292784, 0.44438074, 1.31835646],
       [3.16575281, 1.97021162, 6.12594269, 0.98720836],
       [1.0115348 , 2.61288107, 3.15241031, 0.81024736]])

In [8]:
#我想round保留两位小数 默认是没有小数
a3=a2.round()
a3

array([[6., 9., 0., 1.],
       [3., 2., 6., 1.],
       [1., 3., 3., 1.]])

In [10]:
#数组与数组的计算
a1=np.arange(0,24).reshape((3,8))
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
a2 = np.random.randint(1,10,size=(3,8))
a2

array([[7, 2, 2, 6, 9, 6, 8, 3],
       [8, 1, 8, 3, 8, 8, 5, 7],
       [9, 8, 2, 6, 4, 1, 7, 7]])

In [13]:
a3=a1+a2
# #相减/相除/相乘都是可以的
a3

array([[ 7,  3,  4,  9, 13, 11, 14, 10],
       [16, 10, 18, 14, 20, 21, 19, 22],
       [25, 25, 20, 25, 24, 22, 29, 30]])

In [14]:
a1=np.random.randint(10,20,size=(3,8))#3行8列
a1

array([[10, 15, 11, 15, 18, 10, 17, 11],
       [14, 16, 12, 19, 15, 14, 15, 17],
       [17, 18, 14, 15, 12, 13, 15, 14]])

In [15]:
a2 = np.random.randint(1,10,size=(1,8))
a2

array([[6, 5, 9, 6, 7, 1, 6, 7]])

In [16]:
print(a1+a2)

[[16 20 20 21 25 11 23 18]
 [20 21 21 25 22 15 21 24]
 [23 23 23 21 19 14 21 21]]


In [17]:
#数组与标量间的运算
arr2 = np.array([1,2,3])
arr2

array([1, 2, 3])

In [18]:
arr3=arr2+10
arr3

array([11, 12, 13])

adarray的索引和切片

In [20]:
a=np.array([[1,10,11,20,21],[2,9,12,19,22],[3,8,13,18,23],[4,7,14,17,24],[5,6,15,16,25]])
print(a)

[[ 1 10 11 20 21]
 [ 2  9 12 19 22]
 [ 3  8 13 18 23]
 [ 4  7 14 17 24]
 [ 5  6 15 16 25]]


In [21]:
# ndarray 从0开始去取数据，从零开始
#0-2行
#0-2列
#列表很像的
print(a[:3,:3])

[[ 1 10 11]
 [ 2  9 12]
 [ 3  8 13]]


In [23]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])#创建二维数组
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[0]

array([1, 2, 3])

In [25]:
a1 = np.arange(0,24).reshape((4,6))
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
#数组的转置 T
a2=a1.T
a2

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

布尔索引

In [28]:
a1 = np.arange(0,24).reshape((4,6))
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [29]:
print(a1<10)
#会返回一个新的数组，这个数组中的值全部都是bool类型

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [30]:
a2=a1<10

In [33]:
print(a1[a2])

[0 1 2 3 4 5 6 7 8 9]


In [35]:
#!=,==,>,<,>=,<=以及&(与)和|(或)
a1=np.arange(0,24).reshape((4,6))
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [36]:
a2=a1[(a1==5)|(a1>10)]
print(a2)

[ 5 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [37]:
#值的替换
a1=np.arange(0,24).reshape((4,6))
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
a1[2]=0

In [40]:
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  0  0  0  0  0]
 [18 19 20 21 22 23]]


In [42]:
#where 函数
a1=np.arange(0,24).reshape((4,6))
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [43]:
#把a1中所有小于10的数全部变成1,其余的变成0
a2=np.where(a1<10,1,0)
a2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [44]:
#NAN Not A number 不是一个数字的意思
#INF `Infinity`代表的是无穷大的意思
#NAN=NAN

In [45]:
np.NAN !=np.NAN

True

In [46]:
data = np.random.randint(0,10,size=(3,5)).astype(np.float64)
data

array([[6., 4., 1., 5., 1.],
       [3., 1., 9., 5., 5.],
       [7., 3., 9., 1., 9.]])

In [47]:
data[0,1]=np.NAN

In [48]:
data

array([[ 6., nan,  1.,  5.,  1.],
       [ 3.,  1.,  9.,  5.,  5.],
       [ 7.,  3.,  9.,  1.,  9.]])

In [49]:
#isnan 判断数据里面是不是有nan值
lines=np.where(np.isnan(data))[0]
lines

array([0], dtype=int64)

In [50]:
#使用delete方法删除指定的行 lines 行号 axis=0是删除行 等于1是删除列
data1=np.delete(data,lines,axis=0)

In [51]:
data1

array([[3., 1., 9., 5., 5.],
       [7., 3., 9., 1., 9.]])

Numpy数组合并，分割，元素重复

In [53]:
a1=np.arange(1,7).reshape(2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a2=np.arange(7,13).reshape(2,3)
a2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
#我想把两个数据进行合并 #默认axis=0
np.concatenate((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
#默认axis=0 按行
np.concatenate((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
#axis=1 按列
np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [57]:
#np.vstack #按列合并
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
#np.hstack #按行合并
np.hstack((a1,a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [72]:
#数据split
a3=np.random.randn(5,3)
a3

array([[-0.05736277, -2.13062783,  2.03040342],
       [-0.42270287, -0.97924447, -0.49847372],
       [ 0.22738938, -0.6331441 , -0.55836528],
       [ 0.89217814, -2.53522255,  0.01726336],
       [ 0.78721269,  1.6791499 , -0.23510798]])

In [73]:
np.split(a3,[1,3],axis=0)

[array([[-0.05736277, -2.13062783,  2.03040342]]),
 array([[-0.42270287, -0.97924447, -0.49847372],
        [ 0.22738938, -0.6331441 , -0.55836528]]),
 array([[ 0.89217814, -2.53522255,  0.01726336],
        [ 0.78721269,  1.6791499 , -0.23510798]])]

In [74]:
np.split(a3,[1,2],axis=1)

[array([[-0.05736277],
        [-0.42270287],
        [ 0.22738938],
        [ 0.89217814],
        [ 0.78721269]]),
 array([[-2.13062783],
        [-0.97924447],
        [-0.6331441 ],
        [-2.53522255],
        [ 1.6791499 ]]),
 array([[ 2.03040342],
        [-0.49847372],
        [-0.55836528],
        [ 0.01726336],
        [-0.23510798]])]

In [75]:
np.split(a3,5)

[array([[-0.05736277, -2.13062783,  2.03040342]]),
 array([[-0.42270287, -0.97924447, -0.49847372]]),
 array([[ 0.22738938, -0.6331441 , -0.55836528]]),
 array([[ 0.89217814, -2.53522255,  0.01726336]]),
 array([[ 0.78721269,  1.6791499 , -0.23510798]])]

In [76]:
#排序和唯一值
a1=np.random.randn(6)
a1

array([-0.58314411, -0.25482162,  0.84541229, -0.0459717 , -1.27491326,
       -0.59029619])

In [80]:
# sort 对数据的排序
a1.sort()

In [78]:
a1

array([-1.27491326, -0.59029619, -0.58314411, -0.25482162, -0.0459717 ,
        0.84541229])

In [81]:
#二维数组
a2=np.random.randn(4,3)
a2

array([[-0.18707242, -1.69567986, -1.46991931],
       [ 1.2033235 ,  1.82957324, -0.41051103],
       [-1.47522199, -0.46459387, -0.86597195],
       [-0.99412282, -1.00400307, -0.23989522]])

In [82]:
#默认是按行进行排序
a2.sort()

In [83]:
a2

array([[-1.69567986, -1.46991931, -0.18707242],
       [-0.41051103,  1.2033235 ,  1.82957324],
       [-1.47522199, -0.86597195, -0.46459387],
       [-1.00400307, -0.99412282, -0.23989522]])

In [84]:
a2.sort(axis=0)
#特殊情况
#sort排序时 axis=0是按列

In [86]:
a2

array([[-1.69567986, -1.46991931, -0.46459387],
       [-1.47522199, -0.99412282, -0.23989522],
       [-1.00400307, -0.86597195, -0.18707242],
       [-0.41051103,  1.2033235 ,  1.82957324]])

In [87]:
data=np.array([1,2,3,1,2,3])
data

array([1, 2, 3, 1, 2, 3])

In [88]:
#求里面唯一值的方法
np.unique(data)

array([1, 2, 3])

In [89]:
a4=np.array([[1,2,3],[2,3,4]])
np.unique(a4)

array([1, 2, 3, 4])

In [94]:
#np.in1d 查看数据是不是在里面
np.in1d(data,[1,2])

array([ True,  True, False,  True,  True, False])

In [93]:
np.in1d(a4,[1,3])

array([ True, False,  True, False,  True, False])

In [96]:
#
arr= np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
arr[1,2]

6

In [102]:
arr2=((arr%2==0)&(arr!=0))
arr2

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [103]:
print(arr[arr2])

[ 2  4  6  8 10]


In [104]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [106]:
np.split(arr,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [108]:
#数组各数之和
arr.sum()

66

In [110]:
#数组各数的均值
arr.mean()

5.5

In [112]:
#数组各数的标准差
arr.std()

3.452052529534663